#include "PluginProcessor.h"
#include "PluginEditor.h"

SampleDicerAudioProcessor::SampleDicerAudioProcessor():AudioProcessor(BusesProperties().withOutput("Output",juce::AudioChannelSet::stereo(),true)),state(*this,nullptr,"STATE",layout()){formats.registerBasicFormats();for(int s=0;s<4;++s){auto&rt=rtParameters[(size_t)s];rt.gain=state.getRawParameterValue(id(s,"gain"));rt.pitch=state.getRawParameterValue(id(s,"pitch"));rt.start=state.getRawParameterValue(id(s,"start"));rt.shift=state.getRawParameterValue(id(s,"shift"));rt.fade=state.getRawParameterValue(id(s,"fade"));rt.locked=state.getRawParameterValue(id(s,"lock"));}rtVoices=state.getRawParameterValue("global.voices");rtPte=state.getRawParameterValue("global.pte");rtBurst=state.getRawParameterValue("global.burst");rtBurstRate=state.getRawParameterValue("global.burstRate");rtRandomVolume=state.getRawParameterValue("random.volume");rtRandomPitch=state.getRawParameterValue("random.pitch");rtRandomStart=state.getRawParameterValue("random.start");rtRandomShift=state.getRawParameterValue("random.shift");juce::PropertiesFile::Options options;options.applicationName="Sample Dicer";options.filenameSuffix="settings";options.folderName="Ilya Orange/Sample Dicer";options.osxLibrarySubFolder="Application Support";settings=std::make_unique<juce::PropertiesFile>(options);}
SampleDicerAudioProcessor::~SampleDicerAudioProcessor(){if(settings!=nullptr)settings->saveIfNeeded();}
juce::AudioProcessorValueTreeState::ParameterLayout SampleDicerAudioProcessor::layout(){
  std::vector<std::unique_ptr<juce::RangedAudioParameter>> p;
  for(int s=1;s<=4;++s){auto x="slot"+juce::String(s)+".";
    p.push_back(std::make_unique<juce::AudioParameterFloat>(x+"gain","Volume",-60.f,6.f,0.f));
    p.push_back(std::make_unique<juce::AudioParameterFloat>(x+"pitch","Pitch",-24.f,24.f,0.f));
    p.push_back(std::make_unique<juce::AudioParameterFloat>(x+"start","Start",0.f,.99f,0.f));
    p.push_back(std::make_unique<juce::AudioParameterFloat>(x+"shift","Shift",0.f,250.f,0.f));
    p.push_back(std::make_unique<juce::AudioParameterFloat>(x+"fade","Fade End",.01f,1.f,1.f));
    p.push_back(std::make_unique<juce::AudioParameterBool>(x+"lock","Lock Slot",false));}
  for(auto n:{"volume","pitch","start","shift"})p.push_back(std::make_unique<juce::AudioParameterFloat>("random."+juce::String(n),"Random "+juce::String(n),0.f,1.f,.15f));
  p.push_back(std::make_unique<juce::AudioParameterInt>("global.voices","Maximum Voices",1,16,8));
  p.push_back(std::make_unique<juce::AudioParameterBool>("global.burst","Burst",false));
  p.push_back(std::make_unique<juce::AudioParameterFloat>("global.burstRate","Burst Rate",juce::NormalisableRange<float>(1.f,30.f,.1f,0.45f),8.f));
  p.push_back(std::make_unique<juce::AudioParameterBool>("global.pte","Per-trigger Randomization",false));
  return{p.begin(),p.end()};}
void SampleDicerAudioProcessor::prepareToPlay(double r,int){hostRate=r;heldNotes=0;burstCountdown=0;}
bool SampleDicerAudioProcessor::isBusesLayoutSupported(const BusesLayout& l)const{return l.getMainOutputChannelSet()==juce::AudioChannelSet::mono()||l.getMainOutputChannelSet()==juce::AudioChannelSet::stereo();}
juce::String SampleDicerAudioProcessor::id(int s,const juce::String& n)const{return"slot"+juce::String(s+1)+"."+n;}
bool SampleDicerAudioProcessor::loadSample(int s,const juce::File& f){
  if(!juce::isPositiveAndBelow(s,4)||!f.existsAsFile())return false; std::unique_ptr<juce::AudioFormatReader> r(formats.createReaderFor(f)); if(!r)return false;
  juce::AudioBuffer<float> next(juce::jmin(2,(int)r->numChannels),(int)r->lengthInSamples); r->read(&next,0,next.getNumSamples(),0,true,true);
  slots[(size_t)s].sampleReady.store(false,std::memory_order_release);const juce::ScopedLock guard(lock);slots[(size_t)s].audio=std::move(next);slots[(size_t)s].sourceRate=r->sampleRate;slots[(size_t)s].file=f;slots[(size_t)s].sampleGeneration.fetch_add(1,std::memory_order_release);slots[(size_t)s].displayVoice=-1;slots[(size_t)s].displayPosition.store(-1.f);slots[(size_t)s].sampleReady.store(true,std::memory_order_release);state.state.setProperty("file"+juce::String(s+1),f.getFullPathName(),nullptr);state.state.setProperty("lastFolder",f.getParentDirectory().getFullPathName(),nullptr);if(settings!=nullptr){settings->setValue("lastFolder",f.getParentDirectory().getFullPathName());settings->saveIfNeeded();}return true;}
void SampleDicerAudioProcessor::clearSample(int s){if(!juce::isPositiveAndBelow(s,4))return;auto&slot=slots[(size_t)s];slot.sampleReady.store(false,std::memory_order_release);const juce::ScopedLock guard(lock);slot.audio.setSize(0,0);slot.file=juce::File{};slot.sampleGeneration.fetch_add(1,std::memory_order_release);slot.displayVoice=-1;slot.displayPosition.store(-1.f);state.state.setProperty("file"+juce::String(s+1),juce::String{},nullptr);}
bool SampleDicerAudioProcessor::browse(int s,int direction){if(!juce::isPositiveAndBelow(s,4)||!slots[s].file.existsAsFile())return false;juce::Array<juce::File> fs;
  for(auto e:juce::RangedDirectoryIterator(slots[s].file.getParentDirectory(),false,"*.wav;*.aif;*.aiff;*.flac;*.mp3",juce::File::findFiles))fs.add(e.getFile());
  fs.sort();if(fs.isEmpty())return false;auto i=fs.indexOf(slots[s].file);i=(juce::jmax(0,i)+(direction<0?-1:1)+fs.size())%fs.size();return loadSample(s,fs[i]);}
juce::String SampleDicerAudioProcessor::sampleName(int s)const{return juce::isPositiveAndBelow(s,4)&&slots[s].file.existsAsFile()?slots[s].file.getFileName():"Drop a sample";}
juce::File SampleDicerAudioProcessor::sampleFile(int s)const{return juce::isPositiveAndBelow(s,4)?slots[s].file:juce::File{};}
float SampleDicerAudioProcessor::playheadPosition(int s)const{return juce::isPositiveAndBelow(s,4)?slots[(size_t)s].displayPosition.load():-1.f;}
float SampleDicerAudioProcessor::audioRandom01() noexcept{audioRngState^=audioRngState<<13;audioRngState^=audioRngState>>17;audioRngState^=audioRngState<<5;return(float)(audioRngState&0x00ffffffu)/16777215.f;}
void SampleDicerAudioProcessor::triggerAll(float velocity){const auto maximum=juce::roundToInt(rtVoices->load());const auto pteEnabled=rtPte->load()>.5f;for(size_t slotIndex=0;slotIndex<slots.size();++slotIndex){auto&s=slots[slotIndex];if(!s.sampleReady.load(std::memory_order_acquire))continue;auto chosen=-1;for(int i=0;i<maximum;++i)if(!s.voices[(size_t)i].playing){chosen=i;break;}if(chosen<0){chosen=s.nextVoice%maximum;s.nextVoice=(s.nextVoice+1)%maximum;}auto&v=s.voices[(size_t)chosen];const auto&rt=rtParameters[slotIndex];v.gainDb=rt.gain->load();v.pitch=rt.pitch->load();v.start=rt.start->load();v.shift=rt.shift->load();v.fade=rt.fade->load();if(pteEnabled&&rt.locked->load()<=.5f){auto vary=[this](float value,float minimum,float upper,float amount){auto normalized=(value-minimum)/(upper-minimum);normalized=juce::jlimit(0.f,1.f,normalized+(audioRandom01()*2.f-1.f)*amount);return minimum+normalized*(upper-minimum);};v.gainDb=vary(v.gainDb,-60.f,6.f,rtRandomVolume->load());v.pitch=vary(v.pitch,-24.f,24.f,rtRandomPitch->load());v.start=vary(v.start,0.f,.99f,rtRandomStart->load());v.shift=vary(v.shift,0.f,250.f,rtRandomShift->load());}v.position=-1;v.delay=0;v.velocity=velocity;v.generation=s.sampleGeneration.load(std::memory_order_acquire);v.playing=true;s.displayVoice=chosen;s.displayPosition.store(v.start);}}
void SampleDicerAudioProcessor::renderVoices(juce::AudioBuffer<float>&out){for(int k=0;k<4;++k){auto&s=slots[(size_t)k];const auto generation=s.sampleGeneration.load(std::memory_order_acquire);for(size_t voiceIndex=0;voiceIndex<s.voices.size();++voiceIndex){auto&v=s.voices[voiceIndex];if(!v.playing)continue;if(v.generation!=generation){v.playing=false;continue;}auto step=s.sourceRate/hostRate*std::pow(2.,v.pitch/12.);auto gain=juce::Decibels::decibelsToGain(v.gainDb);auto fadeEnd=v.fade*s.audio.getNumSamples();auto fadeSamples=juce::jmax(1.0,s.sourceRate*.01);if(v.position<0){v.position=v.start*s.audio.getNumSamples();v.delay=juce::roundToInt(v.shift*.001*hostRate);}for(int i=0;i<out.getNumSamples();++i){if(v.delay>0){--v.delay;continue;}auto pos=(int)v.position;if(pos>=s.audio.getNumSamples()-1||v.position>=fadeEnd){v.playing=false;if((int)voiceIndex==s.displayVoice)s.displayPosition.store(-1.f);break;}auto frac=(float)(v.position-pos);auto fadeGain=(float)juce::jlimit(0.0,1.0,(fadeEnd-v.position)/fadeSamples);for(int c=0;c<out.getNumChannels();++c){auto*d=s.audio.getReadPointer(juce::jmin(c,s.audio.getNumChannels()-1));out.addSample(c,i,juce::jmap(frac,d[pos],d[pos+1])*gain*v.velocity*fadeGain);}v.position+=step;}if((int)voiceIndex==s.displayVoice&&v.playing)s.displayPosition.store((float)(v.position/s.audio.getNumSamples()));}}}
void SampleDicerAudioProcessor::processBlock(juce::AudioBuffer<float>& out,juce::MidiBuffer& midi){juce::ScopedNoDenormals n;out.clear();bool started=false;
  for(auto m:midi){auto message=m.getMessage();if(message.isNoteOn()){++heldNotes;triggerAll(message.getFloatVelocity());started=true;}else if(message.isNoteOff())heldNotes=juce::jmax(0,heldNotes-1);else if(message.isAllNotesOff()||message.isAllSoundOff())heldNotes=0;}
  const auto burst=rtBurst->load()>.5f;const auto interval=hostRate/rtBurstRate->load();if(!burst||heldNotes==0)burstCountdown=0;else{if(started||burstCountdown<=0)burstCountdown=interval;burstCountdown-=out.getNumSamples();while(burstCountdown<=0){triggerAll(1.f);burstCountdown+=interval;}}
  const juce::ScopedTryLock guard(lock);if(guard.isLocked())renderVoices(out);}
void SampleDicerAudioProcessor::captureGeneration(){for(int s=0;s<4;++s){previousGeneration.files[(size_t)s]=slots[(size_t)s].file;int index=0;for(auto name:{"gain","pitch","start","shift"})previousGeneration.values[(size_t)s][(size_t)index++]=state.getRawParameterValue(id(s,name))->load();}hasPreviousGeneration=true;}
void SampleDicerAudioProcessor::dice(bool files,bool values){captureGeneration();for(int s=0;s<4;++s){if(state.getRawParameterValue(id(s,"lock"))->load()>.5f)continue;if(files){if(slots[(size_t)s].file.existsAsFile()){for(int n=1+uiRandom.nextInt(12);n>0;--n)browse(s,1);}else{auto path=settings!=nullptr?settings->getValue("lastFolder"):juce::String{};if(path.isEmpty())path=state.state.getProperty("lastFolder").toString();juce::Array<juce::File> candidates;auto folder=juce::File(path);if(folder.isDirectory())for(auto e:juce::RangedDirectoryIterator(folder,false,"*.wav;*.aif;*.aiff;*.flac;*.mp3",juce::File::findFiles))candidates.add(e.getFile());if(!candidates.isEmpty())loadSample(s,candidates[uiRandom.nextInt(candidates.size())]);}}if(values)for(auto name:{"gain","pitch","start","shift"}){auto* p=state.getParameter(id(s,name));auto amount=state.getRawParameterValue("random."+juce::String(juce::String(name)=="gain"?"volume":name))->load();p->setValueNotifyingHost(juce::jlimit(0.f,1.f,p->getValue()+(uiRandom.nextFloat()*2-1)*amount));}}}
void SampleDicerAudioProcessor::back(){if(!hasPreviousGeneration)return;auto current=previousGeneration;captureGeneration();for(int s=0;s<4;++s){if(current.files[(size_t)s].existsAsFile())loadSample(s,current.files[(size_t)s]);else clearSample(s);int index=0;for(auto name:{"gain","pitch","start","shift"})if(auto*p=state.getParameter(id(s,name))){p->setValueNotifyingHost(p->convertTo0to1(current.values[(size_t)s][(size_t)index++]));}}}
void SampleDicerAudioProcessor::getStateInformation(juce::MemoryBlock& b){if(auto x=state.copyState().createXml())copyXmlToBinary(*x,b);}
void SampleDicerAudioProcessor::setStateInformation(const void*d,int z){if(auto x=getXmlFromBinary(d,z)){state.replaceState(juce::ValueTree::fromXml(*x));for(int i=0;i<4;++i){auto p=state.state.getProperty("file"+juce::String(i+1)).toString();if(p.isNotEmpty())loadSample(i,juce::File(p));}}}
juce::AudioProcessorEditor* SampleDicerAudioProcessor::createEditor(){return new SampleDicerAudioProcessorEditor(*this);}juce::AudioProcessor* JUCE_CALLTYPE createPluginFilter(){return new SampleDicerAudioProcessor();}
